kube-prometheus-stack:
  prometheusOperator:
    serviceAccount:
      create: false
    tlsProxy:
      image:
        repository: cablespaghetti/ghostunnel
        tag: latest
    image:
      tag: v0.42.1
    prometheusConfigReloaderImage:
      tag: v0.42.1
  prometheus:
    enabled: true
    serviceAccount:
      create: false
  grafana:
    sidecar:
      image:
        repository: kiwigrid/k8s-sidecar
        tag: 0.1.209
  kube-state-metrics:
    image:
      repository: carlosedp/kube-state-metrics
      tag: v1.9.6
  