kube-prometheus-stack:
  global:
    rbac:
      create: false
  alertmanager:
    serviceAccount:
      create: false
  prometheusOperator:
    serviceAccount:
      create: false
    tlsProxy:
      image:
        repository: cablespaghetti/ghostunnel
        tag: latest
    image:
      tag: v0.39.0
    prometheusConfigReloaderImage:
      tag: v0.39.0
  prometheus:
    enabled: true
    serviceAccount:
      create: false
    prometheusSpec:
      image:
        repository: quay.io/prometheus/prometheus
        tag: v2.21.0
  grafana:
    sidecar:
      image:
        repository: kiwigrid/k8s-sidecar
        tag: 0.1.209
  kube-state-metrics:
    image:
      repository: carlosedp/kube-state-metrics
      tag: v1.9.6
  